---
title: "NNET PRESENTATION"
author: "Marc XU"
date: "-- mars 2019"
output:
  revealjs::revealjs_presentation:
    center: yes
    highlight: kate
    theme: league
    transition: zoom
---
# Neuron Network 

```{r message = FALSE}
#{data-background="neurone.png"}
library("neuralnet")
library("nnet")
library("mclust")
library("caret")
library("ROCR")
library("knitr")
library("GGally")
library("MLmetrics") # calcul de F1.Score
library("mltools") # calcul du coeff de correl. de Matthiew

knitr::opts_chunk$set(
  fig.width = 8, fig.height = 6, 
  fig.path = 'figures/iris_',
  fig.align = "center", 
  size = "tiny", 
  echo = FALSE, 
  eval = TRUE, 
  warning = FALSE, 
  message = FALSE, 
  results = TRUE, 
  comment = "")
```

```{r}
setwd("../Marc")
getwd()
placenta = read.table(".././data/placenta90.138.txt", dec = ".", sep = "\t", header =TRUE)
```

```{r}
# Les fonctions

# La fonction accuracy
acc = function (resultats) {
  return(sum(diag(resultats)) / sum(resultats))
}

# La fonction erreur
err = function (resultats) {
  return(1 - (sum(diag(resultats)) / sum(resultats)))
}

# La fonction sensibilité
sens = function (resultats) {
  if (nrow(resultats) >= 2) {
    return(resultats[2,2] / (resultats[2,2] + resultats[1,2]))
  } else {
    return(NA)
  }
}

# La fonction spécifité
spec = function (resultats) {
  if (nrow(resultats) >= 2) {
    return(resultats[1,1] /(resultats[2,1] + resultats[1,1]))
  } else {
    return(NA)
  }
}

# La fonction F1_Score
scor = function (resultats) {
  return((2 * resultats[2,2]) / (2 * resultats[2,2] + resultats[1,2] + resultats[2,1]))
}

# La fonction ccm
ccm1 = function (resultats) {
  return((resultats[1,1] * resultats[2,2] - resultats[1,2] * resultats[2,1]) / (sqrt((resultats[1,1]+resultats[1,2]) * (resultats[1,1]+resultats[2,1]) * (resultats[2,2]+resultats[1,2]) *  (resultats[2,2]+resultats[2,1]))))
}

# Les fonctions
prediction2 = function (reseau) {
  realite2 = as.numeric(reseau$response)
  prediction2 = reseau$net.result
  results <- data.frame(actual = realite2, prediction = prediction2)
  names(results) <- c("Realité", "Prédiction")
  return(results)
}
perfection2 = function(matrice) {
  acc.app <- acc(matrice)
  err.app <- err(matrice)
  perf.app <- c(acc.app, err.app)
  names(perf.app) <- c("accuracy", "erreur")
  return(perf.app)
}
```


```{r}
placenta[,"Wap"] = scale(placenta[,"Wap"], center = TRUE, scale = TRUE)
table(placenta$CI)
```

# Données PLACENTA

## Les données PLACENTA

```{r}
kable(head(placenta[,c(1:5)]))
```

## Résumés des données
```{r}
summary(placenta[,c(1:5)])
```

## Visualisation des données (plot)
```{r}
placenta.dist <- dist(placenta[,2:nrow(placenta)])
placenta.mds <- cmdscale(placenta.dist)
plot(placenta.mds, col = placenta$Noms)
```

## Visualisation des données (boxplot)

## Visualisation des données (histogramme)


## ACP
```{r}
placenta.acp <- prcomp(as.matrix(placenta[,2:nrow(placenta)]))
plot(placenta.acp)
biplot(placenta.acp)
```

```{r}
placenta$CI_groupe = ifelse(placenta$CI <= 0.5, "petitCI", "grandCI")
```

## Visualisation des données (boxplot)
```{r}
placenta[,ncol(placenta)]
par(mfrow=c(2,2))
for (i in 3:6) {
  titre.boxplot <- paste("boxplot de :", colnames(placenta)[i])
  boxplot(placenta[,i] ~ placenta[,ncol(placenta)])
  title(titre.boxplot)
}
par(mfrow=c(1,1))
```

## Visualisation des données (histogramme)
```{r, eval = FALSE}
par(mfrow=c(4,3))
for (i in 3:5) {
  titre.histogramme <- paste("Histogramme de :", colnames(placenta)[i])
  by(placenta[,i], placenta[,ncol(placenta)], hist, main = titre.histogramme, breaks = 15, xlab = "cm")
}
par(mfrow=c(1,1))
```

# Prédiction
```{r}
petit = as.numeric(placenta$CI_groupe == "petitCI")
grand = as.numeric(placenta$CI_groupe == "grandCI")

data.placenta = data.frame(placenta[,c(1:138)], petit, grand)
ind.app <- sample(1:nrow(data.placenta), 60)
placenta.app <- data.placenta[ind.app,]
placenta.app
placenta.test <- data.placenta[-ind.app,]
```

```{r}
nom.colonnes = colnames(placenta)
placenta2 = placenta[,-c(1,2)]
formule = as.formula(petit + grand ~ a_base + BCUT_PEOE_1 + BCUT_PEOE_2 + BCUT_SLOGP_2 + BCUT_SMR_1 + BCUT_SMR_2 + b_1rotR + b_max1len + GCUT_PEOE_0 + GCUT_SLOGP_0 + GCUT_SLOGP_3 + GCUT_SMR_0 + GCUT_SMR_2 + logS + mutagenic + PEOE_VSA.0 + PEOE_VSA.5 + PEOE_VSA.6 + PEOE_VSA.0.1 + PEOE_VSA_FPOS + rsynth + SlogP_VSA5 + SlogP_VSA8 + SlogP_VSA9 + SMR_VSA5 + AMW + Mv + nTB + nR06 + nR09 + nR10 + nR11 + nR12 + HNar + MSD + Wap + PW3 + PW4 + PJI2 + Lop + T.N..P. + T.O..Cl. + SRW03 + piPC06 + PCD + X3A + X4A + X3Av + X5Av + MATS1m + MATS2m + MATS7m + MATS8m + MATS4v + MATS5v + MATS6v + MATS4e + MATS7e + MATS8e + MATS2p + MATS5p + MATS6p + MATS7p + MATS8p + GATS4m + GATS5m + GATS6m + GATS7m + GATS4v + GATS4e + GATS2p + GATS7p + GATS8p + JGI2 + JGI4 + JGI6 + SHP2 + SPAM + FDI + HOMA + G.O..F. + G.S..F. + G.F..F. + nCp + nR.Cp + nRCOOR + nArCONHR + nRCO + nCONN + nN.C.N. + nRC.N + nArC.N + nRNHR + nArNR2 + nN.N + nN. + nNq + nN.CO.2 + nArOR + nPyrrolidines + ntH.Thiophenes + nThiophenes + nPyridines + nPyridazines + nPyrazines + C.004 + C.005 + C.012 + C.015 + C.020 + C.026 + C.027 + C.029 + C.034 + H.046 + H.047 + H.051 + H.052 + H.054 + O.060 + N.070 + N.071 + N.073 + N.075 + N.076 + N.078 + N.079 + F.081 + Cl.090 + S.109 + P.117 + Ui + MLOGP2 + ALOGP2 + Depressant.50)

reseau.app = neuralnet(formule, data = placenta.app, hidden = c(10,10))
reseau.test = neuralnet(formule, data = placenta.test, hidden = c(10,10))

predire.app = compute(reseau.app, placenta2[,1:136], rep = 1)
predire.test = compute(reseau.test, placenta2[,1:136], rep = 1)

prediction.seto1.app = ifelse(predire1.app$net.result[,1] >= 0.5, 1 ,0)
prediction.seto1.test = ifelse(predire1.test$net.result[,1] >= 0.5, 1 ,0)
prediction.versi1.app = ifelse(predire1.app$net.result[,2] >= 0.4, 1 ,0)
prediction.versi1.test = ifelse(predire1.test$net.result[,2] >= 0.4, 1 ,0)

confiance.seto1.app <- table(prediction.seto1.app, iris.app$seto, dnn = c("predit", "observe"))
confiance.seto1.test <- table(prediction.seto1.test, iris.test$seto, dnn = c("predit", "observe"))
confiance.versi1.app <- table(prediction.versi1.app, iris.app$versi, dnn = c("predit", "observe"))
confiance.versi1.test <- table(prediction.versi1.test, iris.test$versi, dnn = c("predit", "observe"))

```

